---
title: Introduction
author: Luis Francisco Gomez Lopez
date: 2023-07-22
format: 
  beamer:
    theme: AnnArbor
    colortheme: dolphin
    fonttheme: structurebold
    link-citations: true
    linkcolor: blue
    include-in-header:
      - text: |
          \usepackage{booktabs}
          \usepackage{longtable}
          \usepackage{array}
          \usepackage{multirow}
          \usepackage{wrapfig}
          \usepackage{float}
          \usepackage{colortbl}
          \usepackage{pdflscape}
          \usepackage{tabu}
          \usepackage{threeparttable}
          \usepackage{threeparttablex}
          \usepackage[normalem]{ulem}
          \usepackage{makecell}
          \usepackage{xcolor}
lang: en
bibliography: ../r_for_data_science_2_edition_umng.bib
csl: ../apa.csl
editor: visual
---

```{r r_libraries}
#| eval: true
#| echo: false
#| output: false
#| warning: false
#| error: false 
library(tidyverse)
```

# Contents

-   What you will learn
-   What you would not learn
-   References

# What you will learn

![What you will learn [@wickham_r_2023, figure 1.1]](../000_images/001_data_science.png){#fig-001_data_science width="400" height="400"}

# What you will learn

-   **Import**

    -   Take data store outside R and load it into R
    
        -   Files
        -   Databases
        -   Web APIs[^1]
        
[^1]: Application programming interface
    
# What you will learn[^2]
    
-   **Tidy** [@wickham_tidy_2014]

    -   **Data structure**: rectangular tables made up of *rows* and *columns* where every value belongs to a variable and an observation
    
        -   Each variable forms a column
        -   Each observation forms a row
        -   Every cell is a single value
        -   Each type of observational unit forms a table

-   **Transform**

    -   Narrowing in on observations of interest
    -   Creating new variables
    -   Calculating a set of summary statistics

[^2]: Tidying and transforming are called **wrangling**

# What you will learn

-   Main engines of knowledge generation

    -   **Visualization**
    
        -   Show things not expected
        -   Raise new questions
        -   Identify if you are asking the wrong question
        -   Identify if you need to collect different data
        -   Don't scale well because it requires human brains
    
    -   **Models**
    
        -   You need to have clearly defined precise questions
        -   They scale well because are mathematical and computational tools so they require computers
        -   They are based on assumptions so they cannot question its own assumptions
        
# What you will learn

-   **Communication**

    -   Make others understand your results
    
# What you will learn

-   **Programming**

    -   Use in nearly every part of a data science project
    -   You don’t need to be an expert programmer becuase you are a data scientist not a programmer
    -   However, learning more about programming pays off because becoming a better programmer allows you to automate common tasks and solve new problems
    
# What you will learn

-   **80/20 rule**

    -   You can tackle about 80% of every data science project using the tools you will learn
    -   You will need other tools to tackle the remaining 20%
    
# What you would not learn

-   **Modeling**

    -   Use [`tidymodels`](https://www.tidymodels.org/)  
    
        -   The tidymodels framework is a collection of packages for modeling and machine learning using tidyverse principles
        -    *Tidy Modeling with R* [@kuhn_tidy_2022]
        
-   **Big data**

    -   If you are using large data (10GB - 100GB) learn [`data.table`](https://rdatatable.gitlab.io/data.table/)

-   **Python, Julia, and friends**

    -   Data science teams use a mix of languages
    -   If you learn one programming language it will be easy to learn other programming languages but first learn at least one well 
    -   For python start with:
    
        -   *Python for Data Analysis 3 edition* [@mckinney_python_2022]
        -   *Python Data Science Handbook 2 edition* [@vanderplas_python_2023]

# References {.allowframebreaks}
